// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTelegramBot.Database;

namespace WorkoutTelegramBot.Migrations
{
    [DbContext(typeof(WorkoutContext))]
    [Migration("20211105185718_FixSeedingChatData")]
    partial class FixSeedingChatData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkoutTelegramBot.Database.CompletedWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DailyWorkoutMessageId")
                        .HasColumnType("int");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyWorkoutMessageId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("CompletedWorkouts");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.DailyWorkoutMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupChatId")
                        .HasColumnType("int");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupChatId");

                    b.ToTable("DailyWorkoutMessages");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.GroupChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("TelegramGroupChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendlyName = "Old Group",
                            TelegramGroupChatId = -1001538744570L
                        },
                        new
                        {
                            Id = 2,
                            FriendlyName = "Chad",
                            TelegramGroupChatId = -1001548157689L
                        },
                        new
                        {
                            Id = 3,
                            FriendlyName = "Legs",
                            TelegramGroupChatId = -1001763737479L
                        },
                        new
                        {
                            Id = 4,
                            FriendlyName = "Chest",
                            TelegramGroupChatId = -1001761385598L
                        },
                        new
                        {
                            Id = 5,
                            FriendlyName = "Arms",
                            TelegramGroupChatId = -1001476505107L
                        },
                        new
                        {
                            Id = 6,
                            FriendlyName = "Abs",
                            TelegramGroupChatId = -1001742607664L
                        });
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 4,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 5,
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 6,
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 4,
                            ChatId = 3,
                            WorkoutPlanId = 4
                        },
                        new
                        {
                            Id = 5,
                            ChatId = 2,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 6,
                            ChatId = 2,
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 7,
                            ChatId = 2,
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 8,
                            ChatId = 2,
                            WorkoutPlanId = 4
                        });
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstNameCache")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastNameCache")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsernameCache")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Increment")
                        .HasColumnType("int");

                    b.Property<int>("IncrementIntervallInDays")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Increment = 1,
                            IncrementIntervallInDays = 1,
                            Type = "Push-ups"
                        },
                        new
                        {
                            Id = 2,
                            Increment = 1,
                            IncrementIntervallInDays = 7,
                            Type = "Pull-ups"
                        },
                        new
                        {
                            Id = 3,
                            Increment = 1,
                            IncrementIntervallInDays = 1,
                            Type = "Sit-ups"
                        },
                        new
                        {
                            Id = 4,
                            Increment = 1,
                            IncrementIntervallInDays = 1,
                            Type = "Squats"
                        });
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.CompletedWorkout", b =>
                {
                    b.HasOne("WorkoutTelegramBot.Database.DailyWorkoutMessage", "DailyWorkoutMessage")
                        .WithMany("CompletedUsers")
                        .HasForeignKey("DailyWorkoutMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTelegramBot.Database.TelegramUser", "TelegramUser")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTelegramBot.Database.WorkoutPlan", "WorkoutPlan")
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyWorkoutMessage");

                    b.Navigation("TelegramUser");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.DailyWorkoutMessage", b =>
                {
                    b.HasOne("WorkoutTelegramBot.Database.GroupChat", "GroupChat")
                        .WithMany("DailyWorkoutMessages")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChat");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.Subscription", b =>
                {
                    b.HasOne("WorkoutTelegramBot.Database.GroupChat", "Chat")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTelegramBot.Database.WorkoutPlan", "WorkoutPlan")
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.DailyWorkoutMessage", b =>
                {
                    b.Navigation("CompletedUsers");
                });

            modelBuilder.Entity("WorkoutTelegramBot.Database.GroupChat", b =>
                {
                    b.Navigation("DailyWorkoutMessages");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
